apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper-app-deployment
  labels:
    app: scraper-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scraper-app
  template:
    metadata:
      labels:
        app: scraper-app
    spec:
      containers:
        - name: scraper-app-container
          image: scraper-app-image:latest
          ports:
            - containerPort: 3000
          env:
            - name: dev
              value: value1
            - name: prod
              value: value2
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 20
