apiVersion: v1
kind: Service
metadata:
  name: scraper-app-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scraper-app
      tier: backend 
  ports:
    - protocol: TCP
      port: 3000  # Port on which the service will be exposed within the cluster
      targetPort: 3000  # Port on which your application is listening
  type: ClusterIP  
